### ISSUE TITLE
Can u share the project Complete directory??

### ISSUE THREAD

**Issue by noochila** [piotrkawa/deepfake-whisper-features#12]
like share where we should we place pretrained model, where we should  place  dataset,Like share complete directory structure

**Comment by piotrkawa** [comment]
Hi,
there are no requirements for specific locations. You can specify them in a config file (model's checkpoint path, e.g. `configs/training/whisper_frontend_lcnn.yaml`) and by using args of a script (e.g. `train_and_test.py`).

The datasets can be downloaded from official sources - linked in the README. Please note that we used another [metadata file](https://github.com/piotrkawa/deepfake-whisper-features/tree/main?tab=readme-ov-file#datasets).

**Comment by noochila** [comment]
Thank you
