### ISSUE TITLE
inference and custom training

### ISSUE THREAD

**Issue by Hina-Anwar** [piotrkawa/deepfake-whisper-features#9]
How can I use the repo for inference only ? I want to pass audio data and detect if audio is synthesized or real . Also can we train it using our customized data instead of using the datasets you mentioned ?

**Comment by piotrkawa** [comment]
Hi!
1. Inference 
At this moment there is no extracted inference script. 

2. Custom datasets
Yes - all you need to do is to:  1) create a dataset class in `src/datasets`, 2) add it to `DetectionDataset` class (pass root path via constructor and init it in `_init_datasets`).

**Comment by Hina-Anwar** [comment]
ok thanks
